sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: DOwpIf4tQsvfY6SCa9P4B5vVAW1vkksZTlTI5W0t4drG0yKC6CkVDIRAuBmu5M1q3qrcXTUczxjmEM/wbl0VW0YpmFOK8RRhL86Z2P1N7UEqM564hHlwryOZhKxf9XwWEqdWl5q9EujEEcYQQgcCcmLJcM+fychxk7nL86sjlxfsi7e93MjpFS5hgUlaJa6B/ROQn2ION0xtzoVAvcmgh+jAM8QkDIIYdoKce+ZNVGuOxtg5CBnWfvT5oRuADqtwHN4z+gJeLFHSSc5TahoacCPD0iyDlYk/FNw5KtJa533s9DIyxUSj8H9I/C7o7UBBWj8k9XCVLwfwIGEmpagvh2+6zur36aW4vb6MOdwrRVeCL7+fnP5CzZxkMTvJPoESi3gXStBshrIjaVzEJ5yh58o3dWv5XCTYyMu19p6nUfZqWgJdhiktlspYFVqUMbC2iU+siiqKJBx/9ePJYSYA1BOAdJfUcSDwiqae6C/qTLqVgqW9+6zFVX8JUU4Aecg6bS+xO94wdo1iGtqEyRk6m89jd407CeQwCWJ3JkuMxQqLOUR3qRo1HCCqZbmkaC/2HEU5ExcCZwLEl+Bap8LUHmSxT4XP/y0qjOKCOf8kxEFXvooxx86bDDDcTaU0gupBGwTl+E4hnQcZ/Y3IgP9TaXsEJURqUSUEKD31lI7fG/4=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    rooms:
      secure: SIgX3ChS1G78X30l70PKi0sTlyLbDkUpM0SzYhJz207KoY3Qb0Rt29eofXlYSuPEHJLGNIv4ECTKV4ZI9V2rPUO4lxeukaZYudjQ6bStw4x3OCjnuc3bYdCbZHp0+BOclurPIZau6FwJeVI5lm45xsx+dsdhyixg41kmAOVRyMkiUQGmK0jgs/lKVzxSp8Gk/k3DVJ+iyXJSrRUb0BvKKGpyrA65sTWmlwXc0Hvapu64UzHLP9CMQyRdsQ0lh6THKvCd6YpK/IRZNhobUW/4A3fSFkIhOGFI/U/BtzOgU6BmoM9E2QpNzX9erc3QXhmsN04oYOdgU4joY+OAo4BK0Jhz3g2fMbS/hJXOJZ2ZNw9y6zgeK21ey+xebjC5++SFeopDoze5ysKr//Nc76wK53oVRbfDL1l0m8gqLoEldOedB1mqvwq6LxV8Su2Y1kqx9VXG6b4NKDBmM2ATFZlE8q/ilvEGsqXldJJXgwDt9oTseGyvWGBvPmBKR1GZL2vPCZrAHgtCohHXQAO40BVJAmljpcEPU7tQNyd7/g5anyFX64bka9hmFNwbW2NTye1ryO8Dwzp8RjzXEmAZ/kC5kTTgf6MvlrrMIcwvedwocUNNIzEZCq/Mrw0R486fMJqUioT/r1/fb1fflvuHlniKq8dBbCSaLXi/S/2wvyeBd8c=
