sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release
  on:
    tags: true
notifications:
  slack: akerl:KxboLZkca8LOPq5c6u03WcaA
