sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release
  on:
    tags: true
notifications:
  slack:
    secure: KXb8nQkAXiEZnFHKeyZtXCXD2gKkjii03gaREwy7lOAwOmnKGynk5+JFXsPTzVWW0kCSr1rRsQ97fd3A0EANqg8FdrB7dVgEcUpMcwqjR4TpZOMgq/V/49pdg07z3EvFa8vcr+9LTdjh0B+Rhti6VZp977NEd0pTS1br6lIo/p5yyLf3YV8y2hbyOqqamqbeHGC9bFXQYJLaOjYvIJ7NRU9ocGbpZwbJX6M8a2Pcb15fUyPrh8IQSdOg0VdDkGz+SARR8UCEDRI2D1VRPkuXFpAB6x9B+lkI5mFUu7PtSFctI7lr++YsxBOB/sYzE+KII3PFHUO/4pc8jZ/+uQNAP4vP/3Oq51usq2s+OaNw1umj/stdK5B0jnacIv2O1sG128nYsybiZuejlpb30KdZc2EsAcLTryEKrv4CRRNaBrGIZAjijABbzjNAGFWQ23e5nJrrhteudbFt7bRBtKLEuxHpMWThVusy72luX7yyD5fcnmgvItp/me+IasWCvKHIGQwr45J1/zdpPGw5SqzEVyNv+bzBIRzYDmmCaiH0DPxiByjOFLt00KA0Ah2g/XR19NTJDCHijRLdvb8P/E9+owWG490cOPot47nyLhKl6GdWxS19iTsZpRVso44AcGL+aHuZSG54eoiMLqk87BivDFudR+kaPU9SXhMkwcm8Hog=
